version: '3.8'

services:
  # --- API GATEWAY ---
  api-gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - eventos-network

  # --- USER SERVICE ---
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
    networks:
      - eventos-network

  # --- EVENT SERVICE ---
  event-service:
    build: ./event-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
    networks:
      - eventos-network

  # --- EMAIL SERVICE (PYTHON) ---
  email-service:
    build: ./email-service-py # Ajuste para o nome da sua pasta python
    ports:
      - "8090:8090"
    networks:
      - eventos-network
      

networks:
  eventos-network:
    driver: bridge