server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # --- CONFIGURAÇÃO GLOBAL DE CORS ---
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"   
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS           
            allowedHeaders: "*"
            
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      # --- ROTAS ---
      routes:
        # 1. Rota para USER-SERVICE
        - id: user-services
          uri: http://user-service:8081
          predicates:
            - Path=/users/**, /auth/**

        # 2. Rota para EVENT-SERVICE
        - id: event-service
          uri: http://event-service:8082
          predicates:
            - Path=/eventos/**

        # 3. Rota para REGISTRATION-SERVICE (Inscrições)
        - id: registration-service
          uri: http://registration-service:8083
          predicates:
            - Path=/inscricoes/**

        # 4. Rota para ATTENDANCE-SERVICE (Presenças)
        - id: attendance-service
          uri: http://attendance-service:8084
          predicates:
            - Path=/presencas/**

        # 5. Rota para CERTIFICATE-SERVICE
        - id: certificate-service
          uri: http://certificate-service:8085
          predicates:
            - Path=/certificados/**

        # 6. Rota para EMAIL-SERVICE (PYTHON)
        - id: email-service
          uri: http://email-service:8090
          predicates:
            - Path=/email/**